### ISSUE TITLE
Error: java.lang.NullPointerException: Registry Object not present: glassential:glass_dark_ethereal

### ISSUE THREAD

**Issue by SteveStonerson** [bigenergy/glassential-renewed#1]
Hi,

Having replicable client crashes using version glassential-renewed-forge-1.20.1-1.3.0. Going into creative mode will instant crash the client, also while playing will get random client crashes with the same error. 

Have attached crash log.

[crash-2023-12-30_16.31.50-client.txt](https://github.com/bigenergy/glassential-renewed/files/13797346/crash-2023-12-30_16.31.50-client.txt)

**Comment by djnifos** [comment]
![image](https://github.com/bigenergy/glassential-renewed/assets/2243466/9147c591-d91b-4136-950d-7d46fcd5b2cd)
Here's where the fault originates.  (Taken from a dfferent user's latest.log)

full log:
https://mclo.gs/XdhQj6R

**Comment by bigenergy** [comment]
Is the problem only when the jei is installed?

**Comment by bigenergy** [comment]
please try version 1.4.0
//
if you have any problems, please send a full log with a list of mods
