### ISSUE TITLE
Redstone/Luminous Glass recipe

### ISSUE THREAD

**Issue by dragonfireheart** [bigenergy/glassential-renewed#15]
When I am using Just enough Items I noticed that both redstone and luminous glass have the same recipe of 4 glass blocks.  Went to a crafting table and still could not create either of the glass types.  

UPDATE: I forgot to mention that I am using 1.20.4 so release is 2.3.0 of this mod for Fabric

**Comment by bigenergy** [comment]
You can fix the recipe yourself using datapacks or kubejs, unfortunately I no longer support 1.20.4
