### ISSUE TITLE
2.0.1 crash on server only

### ISSUE THREAD

**Issue by DelviousCrafts** [bigenergy/glassential-renewed#2]
latest Glassential update causes a crash on server only due to an attempted class load for client-only class.

[crash report](https://gist.github.com/DelviousCrafts/fcbfe9e2c37ead19e028a82d569da4b1)
[latest log](https://gist.github.com/DelviousCrafts/6804743c2792481cce10b23974b1b33e)

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.20
- Glassential: 2.0.1

**Comment by bigenergy** [comment]
my bad, sorry
@DelviousCrafts pls try this version
[glassential-renewed-forge-1.20.1-2.0.2.zip](https://github.com/bigenergy/glassential-renewed/files/14024268/glassential-renewed-forge-1.20.1-2.0.2.zip)

**Comment by bigenergy** [comment]
> That seems to have fixed the inital issue, but getting a new crash now.
> 
> [crash report](https://gist.github.com/DelviousCrafts/0a88c7a7a98bc855069900b77681150a) [latest log](https://gist.github.com/DelviousCrafts/a94da315e7e8a0ceb13c9d609aa87a7f)

thx for test, sorry)
this version should work
[glassential-renewed-forge-1.20.1-2.0.2-fix.zip](https://github.com/bigenergy/glassential-renewed/files/14024537/glassential-renewed-forge-1.20.1-2.0.2-fix.zip)

**Comment by DelviousCrafts** [comment]
Yes that version appears to have fixed the issue. Thanks for the quick response!

**Comment by bigenergy** [comment]
> Yes that version appears to have fixed the issue. Thanks for the quick response!

thx for report :)
