### ISSUE TITLE
broken textures

### ISSUE THREAD

**Issue by benbenlaw** [bigenergy/glassential-renewed#4]
trapdoors when opened have missing texture
![image](https://github.com/bigenergy/glassential-renewed/assets/42780877/67db4cd1-ada2-4bd5-93e3-9d0e78860377)
thats the orintation thats broken

**Comment by bigenergy** [comment]
Do all Trapdoors have this problem or just one?

**Comment by benbenlaw** [comment]
all of them

**Comment by benbenlaw** [comment]
i think the problem is in the blockstates, in side the trapdoor files there is "moredoors" instead of  "glassential"

**Comment by bigenergy** [comment]
> i think the problem is in the blockstates, inside the trapdoor files there is "moredoors" instead of "glassential"

You use last version?

**Comment by benbenlaw** [comment]
1.20.1- 2.1.2

**Comment by bigenergy** [comment]
thanks for the report, fixed in version 2.1.3
