### ISSUE TITLE
Uploading Texture pack to Modrinth and Curseforge?

### ISSUE THREAD

**Issue by PhraseNeither** [bigenergy/glassential-renewed#5]
Would you be open to uploading the texture pack to Modrinth and Curseforge. This would allow those of use using the fabric version of the mod to use the texture pack. If you don't have the time would you be okay with my uploading the pack with credit?

**Comment by bigenergy** [comment]
what texture pack are you talking about?

**Comment by PhraseNeither** [comment]
I was referring to texture pack included in the mod.

**Comment by bigenergy** [comment]
These are textures only for the mod, I don't understand what you mean.

**Comment by PhraseNeither** [comment]
My apologies. To my knowledge, for the fabric version of this mod which does not support connect to textures, there is no resource pack that supports connected textures.

**Comment by bigenergy** [comment]
I think you should ask the author of the mod fabric to support ctm

**Comment by bigenergy** [comment]
@PhraseNeither now support fabric 1.20.4 with connected textures by fusion mod
https://www.curseforge.com/minecraft/mc-mods/glassential-renewed/files/5352713
