### ISSUE TITLE
The recipes are gone.

### ISSUE THREAD

**Issue by GoldenFurredFox** [bigenergy/glassential-renewed#6]
**Describe the bug**
Going into the game with a recipe viewer mod, trying to view the recipes for anything in the Glassential mod results in no recipe results.

**To Reproduce**
1. Load a world.
2. Open your inventory.
3. Try to view the recipes for anything from Glassential.
4. They don't exist.
(Alternatively, you can use commands to unlock all recipes if you don't have a recipe viewer, then search the recipe book for anything Glassential related.)

**Expected behavior**
The recipes would show up and be craftable.

**Version (please complete the following information):**\
 - Mod Version: 3.0.0
 - NeoForge Version : 21.0.167

**Comment by bigenergy** [comment]
fixed in 3.0.1
