### ISSUE TITLE
Ethereal Glass Panes (and alternate variant panes) cannot be passed through.

### ISSUE THREAD

**Issue by GoldenFurredFox** [bigenergy/glassential-renewed#7]
**Describe the bug**
When placing an Ethereal Glass Pane, the difference from vanilla glass panes is purely visual. You cannot pass through them, non-players cannot pass through Reverse Ethereal Glass Panes, etc.

**To Reproduce**
1. Load a world.
2. Place Ethereal Glass Panes.
3. Try to step through them.
4. You can't.

**Expected behavior**
You should be capable of passing through the panes.

**Version (please complete the following information):**\
 - Mod Version: 3.0.0
 - NeoForge Version : 21.0.167

**Comment by bigenergy** [comment]
pls try in 3.0.1
